version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - misspell
    - unconvert
    - gocritic
  settings:
    gosec:
      severity: medium
      confidence: medium
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - gosec
